# Generated by Django 5.1.2 on 2024-10-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilepictures/default.jpg', null=True, upload_to='profilepictures'),
        ),
    ]
